# Generated by Django 2.0.7 on 2018-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_obj', models.CharField(max_length=20, verbose_name='ID объекта')),
                ('name', models.CharField(max_length=200, verbose_name='Имя объекта')),
                ('dop', models.CharField(blank=True, max_length=250, verbose_name='Дополнительное описание')),
                ('telephone', models.CharField(blank=True, max_length=19, verbose_name='telephone')),
                ('email', models.CharField(blank=True, max_length=55, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объект',
                'ordering': ['-ID_obj'],
            },
        ),
    ]
