# Generated by Django 2.0.7 on 2018-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Передвижения',
                'verbose_name_plural': 'Передвижения',
                'ordering': ['-datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='geo',
            options={'ordering': ['-ID_obj'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
    ]
