# Generated by Django 2.0.7 on 2018-07-27 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180726_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='ID_obj',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='api.Geo'),
            preserve_default=False,
        ),
    ]
