# Generated by Django 2.0.7 on 2018-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movement_id_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='Latitude',
            field=models.CharField(blank=True, max_length=55, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='movement',
            name='Longitude',
            field=models.CharField(blank=True, max_length=55, verbose_name='Долгота'),
        ),
    ]
