# Generated by Django 2.0.7 on 2018-07-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180727_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=2, verbose_name='событие')),
                ('dop', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('logic', models.BooleanField(verbose_name='Открыто/Закрыто')),
                ('ID_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Geo')),
            ],
            options={
                'verbose_name': 'Передвижения',
                'verbose_name_plural': 'Передвижения',
                'ordering': ['-datetime'],
            },
        ),
    ]
