# Generated by Django 2.0.7 on 2018-07-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-datetime'], 'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
    ]
