# Generated by Django 2.0.7 on 2018-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180727_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='admin',
            field=models.BooleanField(default=1, verbose_name='Администрирование'),
            preserve_default=False,
        ),
    ]
