# Generated by Django 2.0.7 on 2018-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_geo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='geo',
            name='user_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='user_name'),
        ),
    ]
