# Generated by Django 2.0.7 on 2018-09-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
