# Generated by Django 2.0.7 on 2018-09-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ID_obj',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Geo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='zoom',
            field=models.CharField(default=1, max_length=2, verbose_name='Zoom'),
            preserve_default=False,
        ),
    ]
