# Generated by Django 2.0.7 on 2018-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180902_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zoom',
            field=models.CharField(blank=True, max_length=2, verbose_name='Zoom'),
        ),
    ]
