# Generated by Django 2.0.7 on 2018-09-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180902_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ID_obj',
        ),
    ]
