# Generated by Django 2.0.7 on 2018-09-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_profile_id_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='select',
            field=models.OneToOneField(default=1, on_delete=None, to='api.Geo'),
            preserve_default=False,
        ),
    ]
