# Generated by Django 2.0.7 on 2018-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='select',
            field=models.CharField(blank=True, max_length=200, verbose_name='Select'),
        ),
    ]
