# Generated by Django 2.0.7 on 2018-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180916_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ID_obj',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, to='api.Geo'),
            preserve_default=False,
        ),
    ]
