# Generated by Django 2.0.7 on 2018-09-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_id_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ID_obj',
        ),
    ]
